class S {
  static const _pt = {
    // Navbar
    'nav_product':  'Produto',
    'nav_pricing':  'Preços',
    'nav_countries':'Países',
    'nav_contact':  'Contacto',
    'nav_cta':      'Começar',
    // Hero
    'hero_title':    'Automatize o seu negócio\ncom agentes de IA',
    'hero_subtitle': 'A plataforma de agentes de IA criada para empresas da CPLP — Angola, Portugal, Moçambique e mais. Suporte, vendas, jurídico e muito mais, disponível 24/7.',
    'hero_cta_primary':   'Começar grátis',
    'hero_cta_secondary': 'Ver demo',
    'hero_countries_label': 'Disponível em 7 países da CPLP',
    // Sectors
    'sectors_title': 'Para todos os sectores',
    'sectors_subtitle': 'Agentes configurados para as necessidades específicas de cada indústria.',
    's_banks':    'Bancos',
    's_banks_d':  'Onboarding digital, KYC e suporte a clientes bancários.',
    's_telco':    'Telecomunicações',
    's_telco_d':  'Activação de serviços, billing e suporte técnico automatizado.',
    's_energy':   'Petróleo & Energia',
    's_energy_d': 'Gestão de contratos, compliance e consultas regulatórias.',
    's_retail':   'Retalho',
    's_retail_d': 'Assistência de compras, devoluções e recomendações personalizadas.',
    's_gov':      'Governo',
    's_gov_d':    'Atendimento ao cidadão, informação pública e serviços digitais.',
    's_sme':      'PMEs',
    's_sme_d':    'Automatize operações e escale o seu negócio com IA acessível.',
    // Agents
    'agents_title': 'Os nossos agentes',
    'agents_subtitle': 'Especialistas de IA prontos a trabalhar para a sua empresa.',
    'a_support':   'Suporte 24/7',
    'a_support_d': 'Responde a clientes a qualquer hora, em qualquer canal.',
    'a_sales':     'Comercial',
    'a_sales_d':   'Qualifica leads, apresenta propostas e fecha negócios.',
    'a_legal':     'Jurídico',
    'a_legal_d':   'Consultas legais contextualizadas para a legislação CPLP.',
    'a_hr':        'Recursos Humanos',
    'a_hr_d':      'Onboarding, políticas internas e gestão de colaboradores.',
    'a_finance':   'Financeiro',
    'a_finance_d': 'Relatórios, análise de custos e resposta a questões financeiras.',
    'a_marketing': 'Marketing',
    'a_marketing_d':'Criação de conteúdo, campanhas e análise de audiências.',
    'kiesse_badge': 'Powered by Dra. Kiesse',
    // Social proof
    'social_title':    'Servimos empresas em 7 países da CPLP',
    'social_subtitle': 'Mais de 50 empresas já automatizam os seus processos com a Serafy.',
    'social_sectors':  'Bancos · Telecoms · Energia · Governo · Retalho · PMEs',
    // Pricing
    'pricing_title':    'Preços simples e transparentes',
    'pricing_subtitle': 'Sem surpresas. Cancele quando quiser.',
    'pricing_month':    '/mês',
    'pricing_popular':  'Mais popular',
    'pricing_enterprise': 'Personalizado',
    'pricing_cta_start':  'Começar agora',
    'pricing_cta_contact':'Falar connosco',
    'plan_starter':   'Starter',
    'plan_growth':    'Growth',
    'plan_scale':     'Scale',
    'plan_enterprise':'Enterprise',
    'feat_agents':    'agentes incluídos',
    'feat_convs':     'conversas/mês',
    'feat_channels':  'canais (Web · WhatsApp)',
    'feat_analytics': 'Analytics básico',
    'feat_analytics_adv': 'Analytics avançado',
    'feat_support_email': 'Suporte por email',
    'feat_support_prio':  'Suporte prioritário',
    'feat_support_ded':   'Gestor dedicado',
    'feat_custom_agents': 'Agentes personalizados',
    'feat_sla':           'SLA garantido',
    'feat_on_premise':    'On-premise disponível',
    // Countries
    'countries_title':    'Disponível na CPLP',
    'countries_subtitle': 'Cobertura legal e linguística adaptada a cada país.',
    'countries_available': 'Disponível',
    // Footer
    'footer_tagline':  'Inteligência artificial para o mundo de língua portuguesa.',
    'footer_product':  'Produto',
    'footer_pricing':  'Preços',
    'footer_countries':'Países',
    'footer_contact':  'Contacto',
    'footer_privacy':  'Política de Privacidade',
    'footer_terms':    'Termos de Serviço',
    'footer_copy':     '© 2026 Serafy Agentics by LILIPTECH. Todos os direitos reservados.',
  };

  static const _en = {
    'nav_product':  'Product',
    'nav_pricing':  'Pricing',
    'nav_countries':'Countries',
    'nav_contact':  'Contact',
    'nav_cta':      'Get started',
    'hero_title':    'Automate your business\nwith AI agents',
    'hero_subtitle': 'The AI agent platform built for CPLP businesses — Angola, Portugal, Mozambique and more. Support, sales, legal and much more, available 24/7.',
    'hero_cta_primary':   'Start for free',
    'hero_cta_secondary': 'Watch demo',
    'hero_countries_label': 'Available in 7 CPLP countries',
    'sectors_title': 'For every sector',
    'sectors_subtitle': 'Agents configured for the specific needs of each industry.',
    's_banks':    'Banking',
    's_banks_d':  'Digital onboarding, KYC and automated customer support.',
    's_telco':    'Telecommunications',
    's_telco_d':  'Service activation, billing and automated technical support.',
    's_energy':   'Oil & Energy',
    's_energy_d': 'Contract management, compliance and regulatory queries.',
    's_retail':   'Retail',
    's_retail_d': 'Shopping assistance, returns and personalised recommendations.',
    's_gov':      'Government',
    's_gov_d':    'Citizen services, public information and digital services.',
    's_sme':      'SMEs',
    's_sme_d':    'Automate operations and scale your business with accessible AI.',
    'agents_title': 'Our agents',
    'agents_subtitle': 'AI specialists ready to work for your business.',
    'a_support':   '24/7 Support',
    'a_support_d': 'Responds to customers at any time, on any channel.',
    'a_sales':     'Sales',
    'a_sales_d':   'Qualifies leads, presents proposals and closes deals.',
    'a_legal':     'Legal',
    'a_legal_d':   'Legal queries contextualised for CPLP legislation.',
    'a_hr':        'Human Resources',
    'a_hr_d':      'Onboarding, internal policies and employee management.',
    'a_finance':   'Finance',
    'a_finance_d': 'Reports, cost analysis and financial Q&A.',
    'a_marketing': 'Marketing',
    'a_marketing_d':'Content creation, campaigns and audience analysis.',
    'kiesse_badge': 'Powered by Dra. Kiesse',
    'social_title':    'We serve businesses in 7 CPLP countries',
    'social_subtitle': 'Over 50 companies already automate their processes with Serafy.',
    'social_sectors':  'Banking · Telecoms · Energy · Government · Retail · SMEs',
    'pricing_title':    'Simple, transparent pricing',
    'pricing_subtitle': 'No surprises. Cancel anytime.',
    'pricing_month':    '/month',
    'pricing_popular':  'Most popular',
    'pricing_enterprise': 'Custom',
    'pricing_cta_start':  'Get started',
    'pricing_cta_contact':'Talk to us',
    'plan_starter':   'Starter',
    'plan_growth':    'Growth',
    'plan_scale':     'Scale',
    'plan_enterprise':'Enterprise',
    'feat_agents':    'agents included',
    'feat_convs':     'conversations/month',
    'feat_channels':  'channels (Web · WhatsApp)',
    'feat_analytics': 'Basic analytics',
    'feat_analytics_adv': 'Advanced analytics',
    'feat_support_email': 'Email support',
    'feat_support_prio':  'Priority support',
    'feat_support_ded':   'Dedicated manager',
    'feat_custom_agents': 'Custom agents',
    'feat_sla':           'Guaranteed SLA',
    'feat_on_premise':    'On-premise available',
    'countries_title':    'Available across CPLP',
    'countries_subtitle': 'Legal and linguistic coverage adapted to each country.',
    'countries_available': 'Available',
    'footer_tagline':  'Artificial intelligence for the Portuguese-speaking world.',
    'footer_product':  'Product',
    'footer_pricing':  'Pricing',
    'footer_countries':'Countries',
    'footer_contact':  'Contact',
    'footer_privacy':  'Privacy Policy',
    'footer_terms':    'Terms of Service',
    'footer_copy':     '© 2026 Serafy Agentics by LILIPTECH. All rights reserved.',
  };

  static String of(String locale, String key) =>
      (locale == 'en' ? _en[key] : _pt[key]) ?? _pt[key] ?? key;
}

// CPLP countries data
const kCplpLanding = [
  (code: 'AO', flag: '🇦🇴', namePt: 'Angola',            nameEn: 'Angola'),
  (code: 'PT', flag: '🇵🇹', namePt: 'Portugal',          nameEn: 'Portugal'),
  (code: 'MZ', flag: '🇲🇿', namePt: 'Moçambique',        nameEn: 'Mozambique'),
  (code: 'CV', flag: '🇨🇻', namePt: 'Cabo Verde',        nameEn: 'Cape Verde'),
  (code: 'ST', flag: '🇸🇹', namePt: 'São Tomé e Príncipe',nameEn: 'São Tomé and Príncipe'),
  (code: 'GW', flag: '🇬🇼', namePt: 'Guiné-Bissau',      nameEn: 'Guinea-Bissau'),
  (code: 'BR', flag: '🇧🇷', namePt: 'Brasil',             nameEn: 'Brazil'),
];
