name: landing_page
description: Serafy.ai public landing page

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
